package com.fortyoneconcepts.valjogen.testsources;

import java.util.Arrays;
import java.util.Objects;
import javax.annotation.Generated;

@Generated(value = "com.fortyoneconcepts.valjogen", date="2014-09-12T19:38Z", comments="Generated by ValjoGen code generator (ValjoGen.41concepts.com) from CustomTemplateInterface")
public final class CustomTemplateClass implements CustomTemplateInterface
{
  // Inserted magic code
  private final Object _object;

  public static CustomTemplateClass valueOf(final Object _object)
  {
    return new CustomTemplateClass(_object);
  }

  private CustomTemplateClass(final Object _object)
  {
    this._object=Objects.requireNonNull(_object);
  }

  @Override
  public final Object getObject()
  {
    return _object;
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(_object);
  }

  @Override
  public boolean equals(final Object arg0)
  {
    if (this == arg0)
      return true;
    if (arg0 == null)
      return false;
    if (getClass() != arg0.getClass())
      return false;

    CustomTemplateClass _other = (CustomTemplateClass) arg0;

    return (Objects.equals(_object, _other._object));
  }

  @Override
  public String toString()
  {
      final StringBuilder _sb = new StringBuilder();
      _sb.append("CustomTemplateClass [");
      _sb.append("_object=");
      _sb.append(_object); 
      _sb.append(']');
      return _sb.toString();
  }
}