package com.fortyoneconcepts.valjogen.testsources;

import java.util.Arrays;
import java.util.Objects;
import javax.annotation.Generated;

@Generated(value = "com.fortyoneconcepts.valjogen", date="2014-11-22T09:48Z", comments="Generated by ValjoGen code generator (ValjoGen.41concepts.com) from com.fortyoneconcepts.valjogen.testsources.ExternalizableMutableInterfaceWithBaseClass")
public final class ExternalizableMutableWithBaseClass extends ExternalizableBaseClass implements ExternalizableMutableInterfaceWithBaseClass
{
  private byte _byte;
  private int _int;
  private long _long;
  private char _char;
  private boolean _boolean;
  private float _float;
  private double _double;
  private String string;
  private Object object;

  public static ExternalizableMutableWithBaseClass valueOf(final byte _byte, final int _int, final long _long, final char _char, final boolean _boolean, final float _float, final double _double, final String string, final Object object)
  {
    ExternalizableMutableWithBaseClass _instance = new ExternalizableMutableWithBaseClass(_byte, _int, _long, _char, _boolean, _float, _double, string, object);
    return _instance;
  }

  public static ExternalizableMutableWithBaseClass valueOf()
  {
    ExternalizableMutableWithBaseClass _instance = new ExternalizableMutableWithBaseClass();
    return _instance;
  }

  public static ExternalizableMutableWithBaseClass valueOf(final int baseValue, final byte _byte, final int _int, final long _long, final char _char, final boolean _boolean, final float _float, final double _double, final String string, final Object object)
  {
    ExternalizableMutableWithBaseClass _instance = new ExternalizableMutableWithBaseClass(baseValue, _byte, _int, _long, _char, _boolean, _float, _double, string, object);
    return _instance;
  }

  public static ExternalizableMutableWithBaseClass valueOf(final int baseValue)
  {
    ExternalizableMutableWithBaseClass _instance = new ExternalizableMutableWithBaseClass(baseValue);
    return _instance;
  }

  private ExternalizableMutableWithBaseClass(final byte _byte, final int _int, final long _long, final char _char, final boolean _boolean, final float _float, final double _double, final String string, final Object object)
  {
    super();
    this._byte=_byte;
    this._int=_int;
    this._long=_long;
    this._char=_char;
    this._boolean=_boolean;
    this._float=_float;
    this._double=_double;
    this.string=Objects.requireNonNull(string);
    this.object=Objects.requireNonNull(object);
  }

  public ExternalizableMutableWithBaseClass()
  {
    super();
  }

  private ExternalizableMutableWithBaseClass(final int baseValue, final byte _byte, final int _int, final long _long, final char _char, final boolean _boolean, final float _float, final double _double, final String string, final Object object)
  {
    super(baseValue);
    this._byte=_byte;
    this._int=_int;
    this._long=_long;
    this._char=_char;
    this._boolean=_boolean;
    this._float=_float;
    this._double=_double;
    this.string=Objects.requireNonNull(string);
    this.object=Objects.requireNonNull(object);
  }

  private ExternalizableMutableWithBaseClass(final int baseValue)
  {
    super(baseValue);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public byte getByte()
  {
   return _byte;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public void setByte(final byte value)
  {
   this._byte=value;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public int getInt()
  {
   return _int;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public void setInt(final int value)
  {
   this._int=value;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public long getLong()
  {
   return _long;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public void setLong(final long value)
  {
   this._long=value;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public char getChar()
  {
   return _char;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public void setChar(final char value)
  {
   this._char=value;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public boolean isBoolean()
  {
   return _boolean;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public void setBoolean(final boolean value)
  {
   this._boolean=value;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public float getFloat()
  {
   return _float;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public void setFloat(final float value)
  {
   this._float=value;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public double getDouble()
  {
   return _double;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public void setDouble(final double value)
  {
   this._double=value;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public String getString()
  {
   return string;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public void setString(final String value)
  {
   this.string=Objects.requireNonNull(value);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public Object getObject()
  {
   return object;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public void setObject(final Object value)
  {
   this.object=Objects.requireNonNull(value);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public void writeExternal(final java.io.ObjectOutput out) throws java.io.IOException
  {
    super.writeExternal(out);

    out.writeByte(_byte);
    out.writeInt(_int);
    out.writeLong(_long);
    out.writeChar((int)_char);
    out.writeBoolean(_boolean);
    out.writeFloat(_float);
    out.writeDouble(_double);
    out.writeUTF(string);
    out.writeObject(object);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public void readExternal(final java.io.ObjectInput in) throws java.io.IOException, ClassNotFoundException
  {
    super.readExternal(in);

    _byte=in.readByte();
    _int=in.readInt();
    _long=in.readLong();
    _char=in.readChar();
    _boolean=in.readBoolean();
    _float=in.readFloat();
    _double=in.readDouble();
    string=in.readUTF();
    object=(Object)in.readObject();
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public int hashCode()
  {
    final int _prime = 31;
    int _result = 1;
    _result = _prime * _result + Byte.hashCode(_byte); 
    _result = _prime * _result + Integer.hashCode(_int); 
    _result = _prime * _result + Long.hashCode(_long); 
    _result = _prime * _result + Character.hashCode(_char); 
    _result = _prime * _result + Boolean.hashCode(_boolean); 
    _result = _prime * _result + Float.hashCode(_float); 
    _result = _prime * _result + Double.hashCode(_double); 
    _result = _prime * _result + Objects.hashCode(string); 
    _result = _prime * _result + Objects.hashCode(object); 
    return _result;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public boolean equals(final Object arg0)
  {
    if (this == arg0)
      return true;

    if (arg0 == null)
      return false;

    if (getClass() != arg0.getClass())
      return false;

    @SuppressWarnings("unchecked")
    ExternalizableMutableWithBaseClass _other = (ExternalizableMutableWithBaseClass) arg0;

    return ((_byte == _other._byte) && (_int == _other._int) && (_long == _other._long) && (_char == _other._char) && (_boolean == _other._boolean) && (Float.floatToIntBits(_float) == Float.floatToIntBits(_other._float)) && (Double.doubleToLongBits(_double) == Double.doubleToLongBits(_other._double)) && Objects.equals(string, _other.string) && Objects.equals(object, _other.object));
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public String toString()
  {
    final StringBuilder _sb = new StringBuilder();
    _sb.append("ExternalizableMutableWithBaseClass [");
    _sb.append("_byte=");
    _sb.append(_byte); 
    _sb.append(", ");
    _sb.append("_int=");
    _sb.append(_int); 
    _sb.append(", ");
    _sb.append("_long=");
    _sb.append(_long); 
    _sb.append(", ");
    _sb.append("_char=");
    _sb.append(_char); 
    _sb.append(", ");
    _sb.append("_boolean=");
    _sb.append(_boolean); 
    _sb.append(", ");
    _sb.append("_float=");
    _sb.append(_float); 
    _sb.append(", ");
    _sb.append("_double=");
    _sb.append(_double); 
    _sb.append(", ");
    _sb.append("string=");
    _sb.append(string); 
    _sb.append(", ");
    _sb.append("object=");
    _sb.append(object); 
    _sb.append(']');
    return _sb.toString();
  }
}