package com.fortyoneconcepts.valjogen.testsources;

import java.util.Arrays;
import java.util.Objects;
import javax.annotation.Generated;

@Generated(value = "com.fortyoneconcepts.valjogen", date="2014-10-16T15:42Z", comments="Generated by ValjoGen code generator (ValjoGen.41concepts.com) from com.fortyoneconcepts.valjogen.testsources.SerializableInterfaceWithBaseClass") 
public final class SerializableWithBaseClass extends BaseClass implements SerializableInterfaceWithBaseClass
{
  private String value;

  public static SerializableWithBaseClass valueOf(final int baseValue, final String value)
  {
    SerializableWithBaseClass _instance = new SerializableWithBaseClass(baseValue, value);
    return _instance;
  }

  private SerializableWithBaseClass(final int baseValue, final String value)
  {
    super(baseValue);
    this.value=Objects.requireNonNull(value);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public String getValue()
  {
   return value;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public void setValue(final String value)
  {
   this.value=Objects.requireNonNull(value);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public int hashCode()
  {
    int _result = Objects.hash(value);
    return _result;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public boolean equals(final Object arg0)
  {
    if (this == arg0)
      return true;

    if (arg0 == null)
      return false;

    if (getClass() != arg0.getClass())
      return false;

    @SuppressWarnings("unchecked")
    SerializableWithBaseClass _other = (SerializableWithBaseClass) arg0;

    return (Objects.equals(value, _other.value));
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public String toString()
  {
    final StringBuilder _sb = new StringBuilder();
    _sb.append("SerializableWithBaseClass [");
    _sb.append("value=");
    _sb.append(value); 
    _sb.append(']');
    return _sb.toString();
  }
}