package com.fortyoneconcepts.valjogen.testsources;

import java.util.Arrays;
import java.util.Objects;
import javax.annotation.Generated;

@Generated(value = "com.fortyoneconcepts.valjogen", date="2014-09-07T15:21Z", comments="Generated by ValjoGen code generator (ValjoGen.41concepts.com) from SimpleInterface")
public final class SimpleClass implements SimpleInterface
{
  private final Object _object;

  private final String _string;

  public static SimpleClass valueOf(final Object _object, final String _string)
  {
    return new SimpleClass(_object, _string);
  }

  private SimpleClass(final Object _object, final String _string)
  {
    this._object=Objects.requireNonNull(_object);
    this._string=Objects.requireNonNull(_string);
  }

  @Override
  public final Object getObject()
  {
    return _object;
  }

  @Override
  public final String getString()
  {
    return _string;
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(_object,_string);
  }

  @Override
  public boolean equals(final Object obj)
  {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;

    SimpleClass _other = (SimpleClass) obj;

    return (Objects.equals(_object, _other._object) && Objects.equals(_string, _other._string));
  }

  @Override
  public String toString()
  {
      final StringBuilder _sb = new StringBuilder();
      _sb.append("SimpleClass [");
      _sb.append("_object=");
      _sb.append(_object); 
      _sb.append(", ");
      _sb.append("_string=");
      _sb.append(_string); 
      _sb.append(']');
      return _sb.toString();
  }
}